### ISSUE TITLE
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate

### ISSUE THREAD

**Issue by skbhati199** [Airsaid/AndroidLocalizePlugin#36]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio  - 4.2.2
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version: 2.3.0
- Android Studio Version: 4.2.2

#### Issue details

Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "My Application" text from Auto language to German language: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=de&client=gtx&dt=t&dj=1&ie=UTF-8&oe=UTF-8&tk=941359.572215

####
Please add new features
Add Google Client ID and API key easy for paid libary

**Comment by Airsaid** [comment]
The 429 error code appears because of too many requests, which temporarily cannot be translated. Solution:

1. Try the translation again later.
2. Switch to other translators.

In addition, you can set the translation interval longer on the settings page to avoid triggering the problem as much as possible.
