### ISSUE TITLE
Android studio chipmunk canary 7 gives error!

### ISSUE THREAD

**Issue by garawaa** [Airsaid/AndroidLocalizePlugin#44]
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "My Application" text from Auto language to *** language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Turalllb** [comment]
Came here to talk about the same problem.
https://stackoverflow.com/questions/16748969/java-net-httpretryexception-cannot-retry-due-to-server-authentication-in-strea/29468005

**Comment by Turalllb** [comment]
![image](https://user-images.githubusercontent.com/28982210/149798766-7ccc1b55-d06f-4c2d-bbb9-d0bc826dbf0a.png)
use google.com  helps @garawaa

**Comment by Turalllb** [comment]
Unfortunately, even with google.com, I received it in a few minutes and everything was interrupted
20:04	Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "Back to order" text from Auto language to Azerbaijani language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Turalllb** [comment]
I got an error when I wanted to translate into a new language, that is, I had to translate all the lines, maybe there were a lot of them. When I translated into a language that has already been partially translated, everything turned out without errors

**Comment by Airsaid** [comment]
It is recommended to use your own api key.
