### ISSUE TITLE
翻译失败: connect timed out

### ISSUE THREAD

**Issue by leoyang1978** [Airsaid/AndroidLocalizePlugin#47]
提示:
com.airsaid.localization.translate.TranslationException: Failed to translate "Whale Booster" text from Auto language to Japanese language: java.net.SocketTimeoutException: connect timed out
使用环境是在国内, 用google翻译. 
vpn可以正常使用, 网页正常打开. 请问这个问题该如何解决

**Comment by Airsaid** [comment]
建议切换到其他翻译器，使用自己的 App Id、Key 信息。

**Comment by Turalllb** [comment]
I also got this error and I know that the reason is the loss of the Internet, this should not lead to an interruption of the process, I should get information about the network error in the log, but attempts to translate should continue. In the latest version, after a network error, the translation process is interrupted, we can start again, we even have a cache so as not to re-translate what has already been translated, but in some cases there may be little cache, so I would prefer the option with repeated attempts to translate if it is SocketTimeOut or SSlHandshakeException and similar network exceptions

**Comment by Airsaid** [comment]
1. The cache is currently available.
2. About the network request, there is still a lot of room for optimization. but I am not currently focused on this. Also welcome to submit PR.
