### ISSUE TITLE
Translate with Google HTTP EXCEPTION

### ISSUE THREAD

**Issue by Swordox972** [Airsaid/AndroidLocalizePlugin#65]
- [ ] Android Studio

- [ ] Google

 Version of Plugin and IDE
- Plugin Version: 2.6.0
- IDE Version: 2021.2.1

 Issue details
When trying to translate with Google, it says HTTP EXCEPTION. Sorry I forgot the exact error and I don't want to retry as I have already associate my Google Api and API KEY. But on Android Studio Google doesn't work for me.

**Comment by Airsaid** [comment]
This error is not related to the plugin, but to the translation service itself.

It is usually caused by frequent translations resulting in denial of access or running out of credit, etc.

You can check the specific error message in the "Event Log" after the error is reported, and go to the Google Translate API documentation to see the corresponding cause.

**Comment by Swordox972** [comment]
In fact I don't speak about the Google(API) but the error occurs on the Google(first choice of the plugin translator). 

Also as I already associated Google(API) (which works perfectly by the way), I didn't want to change again the translator to Google(normal) to retest to see what kind of error it told.

**Comment by Airsaid** [comment]
Okay, I understand. You can go ahead and use Google(API), which is what I recommend.

The first choice is Google just for the convenience of some people who do not want to apply for their own accounts, although convenient, but it is not very stable translation.
